### PR TITLE
Allow to redefine CFLAGS* and OUTPUT directory

### PR DESCRIPTION
**Pull request by dwrobel**
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

### CODE REVIEW

**Comment by dwrobel** [comment]
I created this patch as I'm trying to package the `rtl-wmbus` for `Fedora` and I needed a way to pass distribution `CFLAGS` and `LDFLAGS` to the package.

**Comment by dwrobel** [comment]
Thanks for merging.

FYI in the meantime Frederik forked this project and merged this change also in his repository https://github.com/weetmuts/rtl-wmbus/commit/33fcb282f79ce5f1e39c7b94fe7c428a9de35a3e.
He has also a more changes which aren't in your repository. It would be appreciated if you could try to contact him and agree which version will be maintained and treated as an upstream.

**Comment by xaelsouth** [comment]
Re: [xaelsouth/rtl-wmbus] Allow to redefine CFLAGS* and OUTPUT directory (#8)



Hello Damian,

I have contacted Fredrik. He has updated his fork from mine and I have merged some modifications from him. I would say that https://github.com/xaelsouth/rtl-wmbus is the upstream now.

Xael

Tuesday, January 26, 2021, 11:47:37 AM, you wrote:





Thanks for merging.
FYI in the meantime Frederik forked this project and merged this change also in his repository ***@***.***
He has also a more changes which aren't in your repository. It would be appreciated if you could try to contact him and agree which version will be maintained and treated as an upstream.

**Comment by weetmuts** [comment]
Yep, I verified that all my requested changes have been inserted into Xaels repo.
Actually I already re-cloned my fork from Xael's so they are now effectively the same repo.
Please use Xael's as the upstream if you like Damian.

**Comment by dwrobel** [comment]
Great, thank you!

> Please use Xael's as the upstream if you like Damian.

I marked it as an upstream in https://release-monitoring.org/project/190491/, however due to the lack of any versioning scheme it can't be tracked in a similar way like the  [wmbusmeters](https://release-monitoring.org/project/88654/). Is there any plan to at least tag releases?

**Comment by weetmuts** [comment]
I can make a pull request that addes the build version using the Makefile and the tagged git version.
(Like wmbusmeters does.) I can also add a "rtl_wmbus --version" option to just print the version.
Would you like that Xael?

**Comment by xaelsouth** [comment]
Re: [xaelsouth/rtl-wmbus] Allow to redefine CFLAGS* and OUTPUT directory (#8)



Hello Fredrik,

that would be nice!

Xael

Monday, April 12, 2021, 4:10:42 PM, you wrote:





I can make a pull request that addes the build version using the Makefile and the tagged git version.
(Like wmbusmeters does.) I can also add a "rtl_wmbus --version" option to just print the version.
Would you like that Xael?

**Comment by weetmuts** [comment]
> that would be nice!
>

Sent a pull request! Now the hard part, you have to pick a version number
and tag a release and document it! :-)

Damian! Can you check that the makefile build is satisfactory for your
needs?

**Pull request merged**
